"""add bookings model

Revision ID: 3a3139d63532
Revises: b805ef9590d9
Create Date: 2026-02-12 20:25:31.182267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3139d63532'
down_revision: Union[str, Sequence[str], None] = 'b805ef9590d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'ACTIVE', 'CANCELLED', name='statusenum'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False, foreign_key='items.id'),
    sa.Column('owner_id', sa.Integer(), nullable=False, foreign_key='users.id'),
    sa.Column('rent_id', sa.Integer(), nullable=False, foreign_key='users.id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
