"""add items model

Revision ID: 4097d83de152
Revises: 3a3139d63532
Create Date: 2026-02-12 20:29:01.533406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4097d83de152'
down_revision: Union[str, Sequence[str], None] = '3a3139d63532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=False),
    sa.Column('lon', sa.Numeric(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, foreign_key='users.id'),
    sa.Column('category_id', sa.Integer(), nullable=False, foreign_key='categories.id'),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
