"""addded fix

Revision ID: bbc456406db3
Revises: c047b9e68c7c
Create Date: 2026-04-05 21:24:09.280064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc456406db3'
down_revision: Union[str, Sequence[str], None] = 'c047b9e68c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bookings', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['rent_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # ### end Alembic commands ###
