"""make lat lon nullable

Revision ID: c047b9e68c7c
Revises: cd5cdfb66dff
Create Date: 2026-03-07 21:42:35.965040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c047b9e68c7c'
down_revision: Union[str, Sequence[str], None] = 'cd5cdfb66dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'lat',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('items', 'lon',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'lat',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('users', 'lon',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lon',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('users', 'lat',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.alter_column('items', 'lon',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('items', 'lat',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
