"""add cascade

Revision ID: eece1efcfdbc
Revises: 0c6c364da0d4
Create Date: 2026-04-14 16:43:17.575479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eece1efcfdbc'
down_revision: Union[str, Sequence[str], None] = '0c6c364da0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_item_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_owner_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_rent_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_item_id_fkey', 'bookings', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_owner_id_fkey', 'bookings', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_rent_id_fkey', 'bookings', 'users', ['rent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('itemPhotos_item_id_fkey'), 'itemPhotos', type_='foreignkey')
    op.create_foreign_key('itemPhotos_item_id_fkey', 'itemPhotos', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('items_category_id_fkey'), 'items', type_='foreignkey')
    op.drop_constraint(op.f('items_user_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key('items_category_id_fkey', 'items', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('items_user_id_fkey', 'items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_user_id_fkey', 'items', type_='foreignkey')
    op.drop_constraint('items_category_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_user_id_fkey'), 'items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('items_category_id_fkey'), 'items', 'categories', ['category_id'], ['id'])
    op.drop_constraint('itemPhotos_item_id_fkey', 'itemPhotos', type_='foreignkey')
    op.create_foreign_key(op.f('itemPhotos_item_id_fkey'), 'itemPhotos', 'items', ['item_id'], ['id'])
    op.drop_constraint('bookings_rent_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_owner_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_item_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_rent_id_fkey'), 'bookings', 'users', ['rent_id'], ['id'])
    op.create_foreign_key(op.f('bookings_owner_id_fkey'), 'bookings', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('bookings_item_id_fkey'), 'bookings', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
